### ISSUE TITLE
Host Context

### ISSUE THREAD

**Issue by pixelrebel** [ktbyers/netmiko-ansible#1]
Is there a way to make the host the actual device instead of the agent?  For example, I would prefer to execute commands like this:

`ansible switch -m netmiko_connect -a "..."`
instead of 
`ansible agent -m netmiko_connect -a "host=switch..."`

Is this even possible?

**Comment by ktbyers** [comment]
@pixelrebel Yes, you should be able to specify the following in your ansible Inventory (i.e. use ansible_connection=local)

[switches]
switch1 ansible_connection=local host=10.10.10.227 port=22 username=admin password=password

Let me know if that doesn't work.

**Comment by ktbyers** [comment]
@pixelrebel Note, this GitHub repository is in limbo. I haven't really be doing anything with it. You are welcome to use it, however.

I recently have been doing some work with Cisco IOS and Ansible in the context of NAPALM, see https://pynet.twb-tech.com/blog/automation/napalm-ios.html

**Comment by pixelrebel** [comment]
Thanks @ktbyers, those ansible folks have thought of everything!

How would you suggest I approach this striving to be idempotent?  Diff'ing, the config seems like the best bet.  Does it also make sense to build a wrapper module for each switch type?  Parsing `show` commands and making changes based on this?

**Comment by ktbyers** [comment]
@pixelrebel Idempotent for Cisco IOS (or something similar) is challenging for config changes.

For config changes, what I would try to do for idempotency is to do operations on the entire config file. In other words, does the entire config file match the desired state or not. If it does, leave it alone (i.e. no changes). If it doesn't, replace current config with new config. This is what I implemented in NAPALM.

> Does it also make sense to build a wrapper module for each switch type? Parsing show commands and making changes based on this?

Can you expand on what you are thinking of doing here?

**Comment by pixelrebel** [comment]
Some of our switches only have TFTP available for uploading config files.  So, I thought about wrapping individual switch commands.  For example, if your playbook contains a command to add a VLAN.  That command would first execute a `show vlans`  and check if that VLAN already exists.  If not, then continue with the command. 

Also, consider you have two switches, one with VLAN 10 and the other with VLAN 20.  Now say you want to add VLAN 30 to both switches.  Replacing a config is tricky because you want the two switches to maintain their current VLAN configuration, just share a new common VLAN.  

I guess if our switching infrastructure is all unique snowflakes, ansible isn't going to help much anyway.  Ultimately, I'm trying to leverage switch configurations into chatops.  I'm wondering what the best approach would be.  Any suggestions?

**Comment by ktbyers** [comment]
@pixelrebel 

Yes, you could parse show vlan (check out ntc-ansible and textfsm if you do this https://pynet.twb-tech.com/blog/python/textfsm.html). That could make the output parsing easier.

This could be practical if you have a limited set of changes that you want to make using this method. For example, VLAN adds, deletes, renames.

But it will be a lot of work, if you want to be able to configure a lot of things (VLANs, interfaces, routing protocols, access-lists, etc). 

So I would see the workflow as something like:
1. Receive command to add/delete/rename vlan
2. Check current vlan configuration using Netmiko and/or ntc-ansible
3. If no change, do nothing.
4. If end state is not correct, print what will change, get approval somehow (yes that change is okay).
5. Deploy change

It would be nice to have a rollback method so if things went bad you could somewhat easily rollback.

Kirk

**Comment by pixelrebel** [comment]
> check out ntc-ansible

Already messing with templates, thanks.

> It would be nice to have a rollback method so if things went bad you could somewhat easily rollback.

I thought about this a git repo would be perfect for this, don't you think?  Looks like ntc-ansible has something already built-in.

Thanks for your help!
